apiVersion: v1
kind: Secret
metadata:
  name: azdevops
data:
  AZP_TOKEN: 'PAT created convert to base64'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-deployment
  labels:
    app: azdevops-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      containers:
      - name: azdevops-agent
        #nome do seu ACR que foi criado
        image: nameofyouracr.azurecr.io/azure-devops-agent:latest
        env:
          - name: AZP_URL
            value: "https://dev.azure.com/sua-organizacao" #url da sua organização
          - name: AZP_POOL
            value: "keda-pool"
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_TOKEN
